IF NOT EXISTS (SELECT 1 FROM [master].[sys].[databases] WHERE [name] = 'Weelo_Database')
BEGIN
	CREATE DATABASE Weelo_Database
END
GO

IF EXISTS (SELECT 1 FROM [master].[sys].[databases] WHERE [name] = 'Weelo_Database')
BEGIN
	USE Weelo_Database
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'Weelo')
BEGIN
	EXEC ('CREATE SCHEMA [Weelo];')
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Owner')
BEGIN
	CREATE TABLE [Weelo].[Owner]
	(
		IdOwner INT IDENTITY PRIMARY KEY NOT NULL,
		[Name] VARCHAR(100) NOT NULL,
		[Address] VARCHAR(100) NULL,
		[Photo] VARCHAR(100) NULL,
		[Birthday] DATE NOT NULL
	)
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Property')
BEGIN
	CREATE TABLE [Weelo].[Property]
	(
		IdProperty INT IDENTITY PRIMARY KEY NOT NULL,
		IdOwner INT NOT NULL,
		[Name] VARCHAR(100) NOT NULL,
		[Address] VARCHAR(100) NULL,
		[Price] NUMERIC(19,8) NOT NULL,
		[CodeInternal] VARCHAR(20) NOT NULL,
		[Year] INT NOT NULL,
		FOREIGN KEY (IdOwner) REFERENCES [Weelo].[Owner](IdOwner)
	)
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'PropertyImage')
BEGIN
	CREATE TABLE [Weelo].[PropertyImage]
	(
		IdPropertyImage INT IDENTITY PRIMARY KEY NOT NULL,
		IdProperty INT NOT NULL,
		[File] VARCHAR(100) NOT NULL,
		[Enabled] BIT NOT NULL,
		FOREIGN KEY (IdProperty) REFERENCES [Weelo].[Property](IdProperty)
	)
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'PropertyTrace')
BEGIN
	CREATE TABLE [Weelo].[PropertyTrace]
	(
		IdPropertyTrace INT IDENTITY PRIMARY KEY NOT NULL,
		IdProperty INT NOT NULL,
		[DateSale] DATE NULL,
		[Name] VARCHAR(100) NOT NULL,
		[Value] NUMERIC(19,8) NOT NULL,
		[Tax] NUMERIC(10,4) NOT NULL,
		FOREIGN KEY (IdProperty) REFERENCES [Weelo].[Property](IdProperty)
	)
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'User')
BEGIN
	CREATE TABLE [Weelo].[User]
	(
		IdUser INT IDENTITY PRIMARY KEY NOT NULL,
		[User] VARCHAR(10) NOT NULL,
		[Value] VARCHAR(8) NOT NULL,
		[Email] VARCHAR(50) NOT NULL,
		[Enable] BIT NOT NULL
	)
END
GO


IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Role')
BEGIN
	CREATE TABLE [Weelo].[Role]
	(
		IdRole INT IDENTITY PRIMARY KEY NOT NULL,
		[Role] VARCHAR(10) NOT NULL,
		[Description] VARCHAR(50) NULL
	)
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'UserRole')
BEGIN
	CREATE TABLE [Weelo].[UserRole]
	(
		IdUserRole INT IDENTITY PRIMARY KEY NOT NULL,
		IdUser INT NOT NULL,
		IdRole INT NOT NULL,
		FOREIGN KEY (IdUser) REFERENCES [Weelo].[User](IdUser),
		FOREIGN KEY (IdRole) REFERENCES [Weelo].[Role](IdRole)
	)
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Audit')
BEGIN
	CREATE TABLE [Weelo].[Audit]
	(
		IdAudit INT IDENTITY PRIMARY KEY NOT NULL,
		IdProperty INT NOT NULL,
		IdUser INT NOT NULL,
		IdRole INT NOT NULL,
		[Date] DATETIME NOT NULL,
		[Description] VARCHAR(50) NULL,
		[Location] VARCHAR(20) NOT NULL,
		[Error] VARCHAR(500) NULL,
		FOREIGN KEY (IdUser) REFERENCES [Weelo].[User](IdUser),
		FOREIGN KEY (IdRole) REFERENCES [Weelo].[Role](IdRole)
	)
END
GO